# - Try to find cppzmq
# Once done this will define
#  CPPZMQ_INCLUDE_DIRS - The cppzmq include directories

FIND_PATH(CPPZMQ_INCLUDE_DIR zmq.hpp)

SET(CPPZMQ_INCLUDE_DIRS ${CPPZMQ_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPPZMQ DEFAULT_MSG CPPZMQ_INCLUDE_DIRS)

MARK_AS_ADVANCED(CPPZMQ_INCLUDE_DIRS)